### ISSUE TITLE
Could not connect to server via react-native app : iOS simulator from Expo

### ISSUE THREAD

**Issue by maduperera** [rapPayne/react-native-vs-flutter#11]
Hi,
Thanks for sharing this repo. I was trying to run this and am a bit new to both react-native & flutter and is the same reason I was trying run this to see the difference for my self. The server is up and running and I was able to fetch the apis, such as 
http://127.0.0.1:5000/api/films from the browser and iOS simulators' browser. But when I try to run daam-react-navtive app via expo, it says could not connect to server. I changed the ip address in the hleper.js to my mac ip address as below 

import { Platform } from 'react-native';
export const host = Platform.select(
  {ios: 'http://MY_MAC_IP:5000', android: 'http://10.0.2.2:5000'}
);

Have I changed ip in wrong place or perhaps is there any thing else that I need to do.
Attached are some screenshots

<img width="567" alt="Screen Shot 2020-10-26 at 11 00 59 PM" src="https://user-images.githubusercontent.com/4883128/97206990-d79bb480-178f-11eb-86db-0b2afe094280.png">
<img width="336" alt="Screen Shot 2020-10-26 at 10 19 46 PM" src="https://user-images.githubusercontent.com/4883128/97206996-da96a500-178f-11eb-8eff-d459b410a3f0.png">
<img width="569" alt="Screen Shot 2020-10-26 at 10 18 55 PM" src="https://user-images.githubusercontent.com/4883128/97207011-e08c8600-178f-11eb-88b8-68d26319b655.png">

**Comment by rapPayne** [comment]
You're very welcome, @maduperera . The problem you're experiencing is with Expo. This usually happens when Expo is serving the app on one network and you're connected via another network. Make sure both your laptop (server) is connected to the same WIFI SSID as the emulator/device. 

The second most common cause is when that network has a firewall. This often happens when you're connecting at work. The solution for that would be to turn off the firewall. And if that isn't possible, tether a physical device with a physical cable.

This is (unfortunately) the toughest part of working with React Native which is why I was saying in the Medium article that RN's toolchain is a 'hot mess'. Flutter's is much less painful! 

Good luck!

**Comment by maduperera** [comment]
Thank you very much.
